export const START_FETCHING_POKEMON_LIST = 'START_FETCHING_POKEMON_LIST';
export const SUCCESS_FETCHING_POKEMON_LIST = 'SUCCESS_FETCHING_POKEMON_LIST';
export const ERROR_FETCHING_POKEMON_LIST = 'ERROR_FETCHING_POKEMON_LIST';
export const ADD_POKEMON_TO_LIST = 'ADD_POKEMON_TO_LIST';
